<html lang="en">
<head>
  <link rel="stylesheet" href="/book.css", type="text/css">
</head>
<body>
<div class="container">
    <h2>BOOK</h2>
    <ul class="responsive-table">
        <li class="table-row">
            <div class="col col-1">${book.id}</div>
            <div class="col col-2">${book.name}</div>
            <div class="col col-3">${book.genre}</div>
        </li>
    </ul>
</div>
</body>
</html>